title: madietlx.github.io
author: madietlx
description: >-
  Docker containers, Linux servers, macOS systems, Python, JavaScript and Bash, and everything in between, and more.
url: "https://madietlx.github.io"
twitter_username: madietlx
github_username:  madietlx

theme: minima
plugins:
  - jekyll-feed

show_excerpts: true
